# Generated by Django 2.0.1 on 2020-03-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
